In [1]:
from py_files.common_functions import *
import py_files.fss_itp as fss_itp ## 법령해석 최신
import py_files.fsc_press as fsc_press ## 금융위 보도자료
import py_files.fss_press as fss_press ## 금감원 보도자료
import py_files.fiu_press as fiu_press ## 금융정보분석원 보도자료

today = '260822'
## .env 파일을 수정하였으면 반드시 이 셀을 재실행해야 적용됩니다.
%load_ext autoreload
%autoreload 2

## 브라우저를 열고 각 사이트별로 업데이트 여부만 체크(실제발송 X)

In [2]:
browser = get_browser()

fss_itp.update_check(browser, today) ## 금감원 법령해석
fsc_press.update_check(browser, today) ## 금융위 보도자료
fss_press.update_check(browser, today) ## 금감원 보도자료
fiu_press.update_check(browser, today) ## 금융정보분석원 보도자료

(법령해석) 새로 올라온 정보가 있습니다. 아래 표를 참고해주세요.

,번호,구분,분야,제목,일련번호,등록일
0,4327,비조치의견서,보험,부동산PF 안정화 관련 K-ICS 비율 산출 비조치의견서 직권발급,260013,260630
1,4326,비조치의견서,공통,PF 연착륙 대책 면책 연장 직권 발급,260014,260630
2,4325,비조치의견서,공통,PF 신규자금 건전성 분류 연장 비조치의견서 직권 발급,260015,260630
3,4324,비조치의견서,상호·저축은행업,영업구역내 의무여신비율 규제 관련 비조치의견서 직권발급,260016,260630
4,4323,비조치의견서,상호·저축은행업,저축은행 유가증권 투자한도 관련 비조치의견서 직권발급,260017,260630

(금융위 보도자료) 새로 올라온 자료가 있습니다. 아래 표를 참고해주세요.

                                                  제목     등록일
0  금융위·산업통상부, M.AX(제조AI 대전환) 선도기업들과 ‘피지컬 AI 글로벌 1...  260701
1                    규제지역 추가 지정 관련 「긴급 가계부채 점검회의」 개최  260630
2  국민의 일상을 돌보고, 지역에 활력을 더하는 사회연대경제 - 관계부처 합동 「사회연...  260630
3  희망하는 모든 청년에게 1:1 맞춤형 재무상담을 제공합니다. - 청년 모두를 위한 ...  260630
4  보험업권의 과도한 판매수수료 경쟁을 방지하고, 수수료에 대한 소비자의 알권리를 제고...  260630
5                       새도약기금, 사회 취약계층 장기 연체채권 3차 소각  260630
6  진화하는 피싱범죄도 도망칠 곳 없다! 6월 30일부터 신종피싱 이용 의심계좌의 거래...  260630
7  현장 전문가들과 함께 정책서민금융을 설계해 나갑니다. - 「포용금융 전략 추진단」 ...  260629
8        6.29일부터 중·저신용 취약차주를 위한 ‘중금리 생활안정대출’이 출시됩니다.  260629
9  금융소비자의 눈높이에서 금융소비자 정책을 평가하겠습니다. - 금융위원장, ｢금융소비...  260629

(금감원 보도자료)새로 올라온 자료가 있습니다. 아래 표를 참고해주세요.

,번호,제목,담당부서,등록일,첨부파일,영상,조회수
0,20694,제13차 지정대리인 신청 접수 개시,디지털금융총괄국,260701,,,102
1,20693,「보험점검센터」는 공공기관이 아닙니다 개인정보 제공 동의 요청에 유의하세요.,보험검사3국,260701,,,104
2,20692,"금융소비자에게 유익한 정보를 필요할 때, 이해하기 쉽게, 적극적으로 전해드리겠습니다.",소비자소통국/소비자보호감독총괄국/소비자피해예방국/소비자권익보호국/공보실,260701,,,103
3,20691,보이스피싱 피해자의 불편 해소 및 보호 강화를 위해 금융권 업무 프로세스를 개선하였습니다,금융사기대응단/은행감독국/중소금융감독국,260701,,,1022
4,20690,금융과 경제생활 과목 담당 교사 양성 지원을 위해 여름방학 금융과목 교사 연수를 실...,금융교육국,260701,,,779
5,20689,규제지역 추가 지정 관련 「긴급 가계부채 점검회의」 개최,은행리스크감독국/보험감독국/중소금융감독국/여신금융감독국,260630,,,2172
6,20688,희망하는 모든 청년에게 맞춤형 재무상담을 제공합니다,금융교육국,260630,,,2560
7,20687,"보험업권의 과도한 판매수수료 경쟁을 방지하고, 수수료에 대한 소비자의 알권리를 제고...",보험감독국,260630,,,2790
8,20686,보험회사의 약관대출 대출정보 관리방식 관행이 개선됨에 따라 7월 1일부터 약관대출의...,소비자보호감독총괄국,260630,,,2651
9,20685,금감원-서울시 보이스피싱 예방 공동 캠페인 실시,금융사기대응단,260630,,,2413

DateParseError: Unknown datetime string format, unable to parse: 2026-06-30 / 조회수: 138, at position 0

## 실제 자료 추출 및 이메일 발송 영역

In [ ]:
fss_itp.notice_fss_ipt(browser, today) ## 금감원 법령해석

In [ ]:
fsc_press.notice_fsc_press(browser, today) ## 금융위 보도자료

In [3]:
fss_press.notice_fsc_press(browser, today) ## 금감원 보도자료

총 3개의 이메일을 발송하였습니다. 상세 리스트는 아래 표를 참고해주세요.

                                                보도자료      날짜
0                공신력 있는 녹색금융 실무 전문가 첫 배출 탄소중립 금융 뒷받침  250804
1                           슬기로운 금융생활! e-금융교육센터 톺아보기  250804
2  「외부감사 및 회계 등에 관한 규정 시행세칙」상 감리결과 조치양정기준 등을 일부 개...  250803

In [5]:
fiu_press.notice_fiu_press(browser, today) ## 금융정보분석원 보도자료

(금융정보분석원 보도자료) 총 1개의 이메일을 발송하였습니다. 상세 리스트는 아래 표를 참고해주세요.

                                                보도자료      날짜
0  [보도자료] 금융회사의 자금세탁방지(AML) 전문성 강화와 자발적 개선을 유도하겠습니다.  260303